name: Build

on: [push, pull_request]

jobs:
  appimage:
    name: AppImage
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y cmake qt5-default libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev gr-osmosdr gr-fcdproplus liborc-0.4-dev
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Compile
        working-directory: build
        run: make
      - name: Build AppImage
        run: ./appimage.sh
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: appimage
          path: Gqrx-*.AppImage
